mike-neck/graalvm-native-image-plugin

README.md

see https://www.graalvm.org/docs/reference-manual/native-image/#image-generation-options

fix parameter in readme example

---

README.md

Add github actions status badge to readme

---

.github/workflows/gradle.yml
src/main/java/org/mikeneck/graalvm/GraalVmHome.java
src/main/java/org/mikeneck/graalvm/NativeImageArguments.java
src/main/java/org/mikeneck/graalvm/NativeImageExtension.java
src/main/java/org/mikeneck/graalvm/NativeImageTask.java
src/test/java/org/mikeneck/graalvm/GraalVmHomeTest.java

* Add fall back to `native-image.cmd` for Windows OS.

Fix windows path

---

src/main/java/org/mikeneck/graalvm/NativeImageArguments.java
src/main/java/org/mikeneck/graalvm/NativeImageExtension.java
src/main/java/org/mikeneck/graalvm/NativeImageTask.java

It seems lack of `@InputFile` annotation leads to unexpected UP-TO-DATE.
This will Fix #12 .

Fix issue of up-to-date calculation

---

README.md
build.gradle

* gradle version propery 0.2.1
* document changed to use version 0.2.1

version 0.2.1

---

README.md
example/.github/workflows/release.yml
example/build.gradle

Document improve

---

.github/workflows/gradle.yml
.github/workflows/release.yml
release.sh

Do pushing tag and releasing plugin on merge with title release/xxx

---

src/main/java/org/mikeneck/graalvm/DefaultInstallNativeImageTask.java

fix incompatible behavior at gradle 6.5

---

src/functionalTest/java/org/mikeneck/graalvm/GraalvmNativeImagePluginFunctionalTest.java

Fix #36 
add wraning-mode all option to functional test execution, to know the alert.

add alert of illegal usege of Property/Provider

---

README.md
src/functionalTest/java/org/mikeneck/graalvm/GenerateConfigFileTaskTest.java
src/functionalTest/resources/config-kotlin-project/build-gradle-kts.txt
src/functionalTest/resources/config-kotlin-project/src_main_java_com_example_Reader-java.txt
src/functionalTest/resources/config-kotlin-project/src_main_kotlin_com_example_App-kt.txt
src/functionalTest/resources/config-kotlin-project/src_main_resources_META--INF_services_com-example-Reader.txt
src/functionalTest/resources/config-kotlin-project/src_main_resources_help-txt.txt
src/main/java/org/mikeneck/graalvm/DefaultGenerateNativeImageConfigTask.java
src/main/java/org/mikeneck/graalvm/GenerateNativeImageConfigTask.java
src/main/kotlin/GraalVmNativeImagePlugin.kt
src/main/kotlin/org/mikeneck/graalvm/GenerateNativeImageConfigTaskWrapper.kt

improve documents and kotlin dsl

---

.github/workflows/release.yml

Fix #49 
- use action to comment version

Add comment on PR

---

build.gradle
src/functionalTest/java/org/mikeneck/graalvm/FunctionalTestContext.java
src/functionalTest/java/org/mikeneck/graalvm/GenerateConfigFileTaskTest.java
src/functionalTest/java/org/mikeneck/graalvm/GraalvmNativeImagePluginFunctionalTest.java
src/test/java/org/mikeneck/graalvm/GraalVmHomeTest.java
src/test/java/org/mikeneck/graalvm/GraalvmNativeImagePluginTest.java
src/test/java/org/mikeneck/graalvm/OutputDirectoryProviderTest.java
src/test/java/org/mikeneck/graalvm/config/JniConfigTest.java
src/test/java/org/mikeneck/graalvm/config/MethodUsageTest.java
src/test/java/org/mikeneck/graalvm/config/ProxyConfigTest.java
src/test/java/org/mikeneck/graalvm/config/ReflectConfigTest.java
src/test/java/org/mikeneck/graalvm/config/ResourceConfigTest.java

Migrate JUnit4 to JUnit Platform

---

build.gradle
src/functionalTest/java/org/mikeneck/graalvm/Case60ProxyUsageArrayTest.java
src/functionalTest/java/org/mikeneck/graalvm/FunctionalTestContext.java
src/functionalTest/resources/case60-proxy-usage-array/build-gradle-kts.txt
src/functionalTest/resources/case60-proxy-usage-array/src_main_java_com_example_App-java.txt
src/functionalTest/resources/case60-proxy-usage-array/src_main_java_com_example_ExitCode-java.txt
src/functionalTest/resources/case60-proxy-usage-array/src_main_java_com_example_Printer-java.txt
src/main/java/org/mikeneck/graalvm/config/ProxyUsage.java
src/test/java/org/mikeneck/graalvm/config/ProxyConfigTest.java
src/test/java/org/mikeneck/graalvm/config/ProxyUsageTest.java
src/test/java/org/mikeneck/graalvm/config/comparable/Assert.java
src/test/resources/config/proxy-config-3.json

Make ProxyUsage to be subclass of TreeSet<String>

---

.github/workflows/release.yml

Release by workflow dispatch

---

.github/workflows/versions.yml
.gitignore
version-tests/prepare.sh

Add Test to Gradle versions

---

.gitignore
version-tests/prepare.sh

fix github actions problem

---

src/functionalTest/java/org/mikeneck/graalvm/GenerateConfigFileTaskTest.java
src/functionalTest/resources/config-project/build-gradle.txt
src/functionalTest/resources/config-project/src_main_java_com_example_App-java.txt

remove MethodHandle, because it cannot be transformed to native-image

---

.github/workflows/auto-update-versions.yml
script/generate-versions.sh

Fix Auto-Update

---

script/versions.jq

Fix env option

---

src/functionalTest/java/org/mikeneck/graalvm/Case93WithoutJarTaskWithDifferentConfiguration.java
src/functionalTest/java/org/mikeneck/graalvm/FunctionalTestContext.java
src/functionalTest/java/org/mikeneck/graalvm/Gradlew.java
src/functionalTest/java/org/mikeneck/graalvm/SubProject.java
src/functionalTest/java/org/mikeneck/graalvm/TestProject.java
src/functionalTest/java/org/mikeneck/graalvm/TestProjectSetup.java
src/functionalTest/resources/case93-subproject-app/build-gradle.txt
src/functionalTest/resources/case93-subproject-app/lib_src_main_java_com_example_MessageProvider-java.txt
src/functionalTest/resources/case93-subproject-app/sub_src_main_java_com_example_App-java.txt
src/functionalTest/resources/case93-without-jar-with-different-configuration/build-gradle.txt
src/functionalTest/resources/case93-without-jar-with-different-configuration/child_src_main_java_com_example_MessageProvider-java.txt
src/functionalTest/resources/case93-without-jar-with-different-configuration/src_main_java_com_example_App-java.txt
src/main/java/org/mikeneck/graalvm/DefaultNativeImageTask.java
src/main/java/org/mikeneck/graalvm/NativeImageConfig.java
src/main/java/org/mikeneck/graalvm/NativeImageTask.java
src/main/java/org/mikeneck/graalvm/nativeimage/NativeImageArguments.java
src/main/java/org/mikeneck/graalvm/nativeimage/UnixLikeOsArguments.java
src/main/java/org/mikeneck/graalvm/nativeimage/WindowsNativeImageArguments.java
src/main/kotlin/GraalVmNativeImagePlugin.kt

Provide classpath API for users not wish to use Jar Task

---

.github/workflows/release.yml

- remove comment on PR.
- insert additional step to set no semantic version string.

fix github actions error

---

src/main/java/org/mikeneck/graalvm/config/ClassUsage.java
src/main/java/org/mikeneck/graalvm/config/FieldUsage.java
src/test/java/org/mikeneck/graalvm/config/ReflectConfigTest.java
src/test/resources/config/reflect-config-case-98.json

Fix #98
- ClassUsage.allPublicMethods
- FieldUsage.allowUnsafeAccess

Add Lacking Properties

---

version-tests/test.sh

Fix #105
- Use built plugin, instead of using published one.

Fix: build(versions tests) failure after api change

---

README.md
src/main/kotlin/GraalVmNativeImagePlugin.kt

Document maintenance

---

src/main/java/org/mikeneck/graalvm/config/ClassUsage.java
src/test/java/org/mikeneck/graalvm/config/ReflectConfigTest.java
src/test/resources/config/reflect-config-case-109.json

Add 2 fields to ClassUsage

---

src/main/java/org/mikeneck/graalvm/config/BooleanMergeable.java
src/main/java/org/mikeneck/graalvm/config/ClassUsage.java
src/main/java/org/mikeneck/graalvm/config/FieldUsage.java
src/main/java/org/mikeneck/graalvm/config/FieldUsages.java
src/test/java/org/mikeneck/graalvm/config/CanBeMergeWithDatum.java
src/test/java/org/mikeneck/graalvm/config/FieldUsageCompareTo.java
src/test/java/org/mikeneck/graalvm/config/FieldUsageTest.java
src/test/java/org/mikeneck/graalvm/config/FieldUsagesTest.java
src/test/java/org/mikeneck/graalvm/config/ReflectConfigTest.java
src/test/resources/config/reflect-config-case-111.json

Add some fields to config classes

---

.github/workflows/gradle.yml
.github/workflows/release.yml

Adjust github actions

---

src/functionalTest/java/org/mikeneck/graalvm/Case115JvmArgs.java
src/functionalTest/java/org/mikeneck/graalvm/TestProjectSetup.java
src/functionalTest/resources/case-115-jvm-args/build-gradle-kts.txt
src/functionalTest/resources/case-115-jvm-args/src_main_java_com_example_App-java.txt
src/functionalTest/resources/case-115-jvm-args/src_main_resources_test-txt.txt
src/main/java/org/mikeneck/graalvm/DefaultGenerateNativeImageConfigTask.java
src/main/java/org/mikeneck/graalvm/GenerateNativeImageConfigTask.java
src/main/java/org/mikeneck/graalvm/GraalvmNativeImagePlugin.java
src/main/java/org/mikeneck/graalvm/JavaExecution.java
src/main/java/org/mikeneck/graalvm/JavaExecutionImpl.java
src/main/java/org/mikeneck/graalvm/JavaExecutionOutput.java

add jvmArguments method to generateNativeImageConfig task

---

.sdkmanrc
build.gradle
src/functionalTest/java/org/mikeneck/graalvm/SerializationConfigTest.java
src/functionalTest/java/org/mikeneck/graalvm/TestParameterResolverHandler.java
src/functionalTest/java/org/mikeneck/graalvm/TestProject.java
src/functionalTest/java/org/mikeneck/graalvm/TestProjectSetup.java
src/functionalTest/resources/serialization-config/build-gradle.txt
src/functionalTest/resources/serialization-config/src_main_java_com_example_App-java.txt
src/functionalTest/resources/serialization-config/src_main_java_com_example_object_Bar-java.txt
src/functionalTest/resources/serialization-config/src_main_java_com_example_object_Foo-java.txt
src/main/java/org/mikeneck/graalvm/DefaultMergeNativeImageConfigTask.java
src/main/java/org/mikeneck/graalvm/MergeNativeImageConfigTask.java
src/main/java/org/mikeneck/graalvm/NativeImageConfigurationFiles.java
src/main/java/org/mikeneck/graalvm/config/ConstructorUsage.java
src/main/java/org/mikeneck/graalvm/config/SerializationConfig.java
src/main/java/org/mikeneck/graalvm/config/task/ConfigFileConfiguration.java
src/main/java/org/mikeneck/graalvm/config/task/ConfigFileProviders.java
src/main/java/org/mikeneck/graalvm/config/task/DefaultMergeConfigFileWork.java
src/main/java/org/mikeneck/graalvm/nativeimage/ConfigurationFiles.java
src/test/java/org/mikeneck/graalvm/config/ConstructorUsageTest.java
src/test/java/org/mikeneck/graalvm/config/JsonFile.java
src/test/java/org/mikeneck/graalvm/config/SerializationConfigTest.java
src/test/java/org/mikeneck/graalvm/config/TestJsonReader.java
src/test/java/org/mikeneck/graalvm/config/task/ConfigFileProvidersTest.java
src/test/resources/config/serialization-config-1.json
src/test/resources/config/serialization-config-2.json
src/test/resources/config/serialization-config-3.json
src/test/resources/config/serialization-config-4.json

Add support for serialization-config.json

---

README.md
src/functionalTest/java/org/mikeneck/graalvm/Case145SharedLibrary.java
src/functionalTest/resources/case-145-main-class-name/build-gradle.txt
src/functionalTest/resources/case-145-main-class-name/src_main_java_com_example_Main-java.txt
src/functionalTest/resources/case-145-main-class-name/src_main_kotlin_com_example_Lib-kt.txt
src/functionalTest/resources/case-145-shared-library/build-gradle.txt
src/functionalTest/resources/case-145-shared-library/src_main_java_com_example_LibInterface-java.txt
src/functionalTest/resources/case-145-shared-library/src_main_kotlin_com_example_Lib-kt.txt
src/functionalTest/resources/kotlin-project/build-gradle-kts.txt
src/main/java/org/mikeneck/graalvm/BuildExecutableOption.java
src/main/java/org/mikeneck/graalvm/BuildExecutableOptionExtended.java
src/main/java/org/mikeneck/graalvm/BuildType.java
src/main/java/org/mikeneck/graalvm/BuildTypeConfiguration.java
src/main/java/org/mikeneck/graalvm/BuildTypeSelector.java
src/main/java/org/mikeneck/graalvm/DefaultNativeImageTask.java
src/main/java/org/mikeneck/graalvm/NativeImageConfig.java
src/main/java/org/mikeneck/graalvm/NativeImageTask.java
src/main/java/org/mikeneck/graalvm/NativeImageTaskFactory.java
src/main/java/org/mikeneck/graalvm/nativeimage/BuildTypeOption.java
src/main/java/org/mikeneck/graalvm/nativeimage/NativeImageArguments.java
src/main/java/org/mikeneck/graalvm/nativeimage/NativeImageArgumentsFactory.java
src/main/java/org/mikeneck/graalvm/nativeimage/NativeImageState.java
src/main/java/org/mikeneck/graalvm/nativeimage/UnixLikeOsArguments.java
src/main/java/org/mikeneck/graalvm/nativeimage/UnixLikeOsArgumentsFactory.java
src/main/java/org/mikeneck/graalvm/nativeimage/WindowsNativeImageArguments.java
src/main/java/org/mikeneck/graalvm/nativeimage/WindowsNativeImageArgumentsFactory.java
src/main/java/org/mikeneck/graalvm/nativeimage/options/type/BuildExecutable.java
src/main/java/org/mikeneck/graalvm/nativeimage/options/type/BuildSharedLibrary.java
src/main/kotlin/GraalVmNativeImagePlugin.kt

Add shared library feature
